# working example configuration to deploy a madek instance using Cider-CI

jobs:
  deploy_madek:
    name: Deploy Madek

    context:
      task_defaults:
        max_trials: 1
        git_options: {submodules: {include_match: ^.*$}}
        aggregate_state: satisfy-last
        traits:
          Ansible 2: yes
          git-crypt: yes
          ci-executor.madek: yes

        environment_variables:
          LANG: "en_US.UTF-8"

      tasks:
        deploy:
          exclusive_global_resources:
            "madek.example.com": true
          environment_variables:
            HOSTS_FILE: hosts

          scripts:
            deploy:
              start_when:
                git-crypt is unlocked: {script_key: unlock}
                only when we are on the head of master branch: {script_key: check-head-of-master}

              timeout: 30 minutes
              body: cd Madek/deploy && ansible-playbook -i "../../${HOSTS_FILE}" play_setup-and-deploy.yml

            check-head-of-master:
              body: |
                set -eux
                git fetch --all
                [[ $(git log -n 1 --pretty=%H HEAD -- ) == $(git log -n 1 --pretty=%H origin/master -- ) ]]

            unlock:
              body: git crypt unlock && ls -R group_vars
